services:
  db:
    container_name: db
    image: postgres:15
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 20
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - jb-network

  web:
    container_name: web
    build:
      context: .
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - jb-network

networks:
  jb-network:
    name: jb-network
    driver: bridge

volumes:
  pg_data:
