# Generated by Django 4.2.16 on 2024-09-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
