# Generated by Django 4.2.16 on 2024-09-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_agencement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Titre')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Agencement',
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Titre')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Mobilier',
            },
        ),
        migrations.DeleteModel(
            name='Agencement',
        ),
    ]
