name: Django

on: [push]

jobs: 
    test:
        name: Run unit tests
        runs-on: ubuntu-22.04
        environment: test
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Checkout
              uses: actions/checkout@v2 

            - name: Test
              run: |
                echo "DJANGO_ENV=test" >> $GITHUB_ENV
                docker compose -f docker-compose-test.yml up
